services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.compose
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: dockerfile
        - action: rebuild
          path: compose.yaml
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock


  #postgresql
  
  db_service:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "1234:5432"
    expose:
      - "1234"
    volumes:
      - timescale_db_data:/var/lib/postgresql/data


volumes:
  timescale_db_data:

